language: c++
os:
- linux
sudo: required
group: travis_lts
git:
  depth: 1000000
env:
  global:
    - secure: "AjDDMlaXOePqJM5FX60RE44f12XspV2FqkCszF2mDk0LwMkzTCzyt7YbUU8Pxt1ABmtszzUgvilGP4Sj5qZq3aa/aAm0POKiTYua34HHn3cQ8q6Kx2aeZ9zSZncE1axj3W1lTjkIeqc6H8tp4yIqvh6lhu6SiOO9yfJI+f0pSxLBWHOkV56lmr8aRD4xe13BiNiwa/EBCdnUEs+PIb18djFwZhHdWW8kBmUkYrL3u4b3AdOqkZgFTA+jVYrOwTK9Oya/LsWELpL630pc1xHRDKTWfrKQYCiLVDlyKsRy1GmZP9nveES+1XBg0SW7T9FDP/7XuQybw1MlO/CGbPAV92b1yjNy3/FYhVVRF5WtSveHcqeFTY34jqKYc5cCtlz/mw6dHLlkXA+bPg4OW2JoscP1TdjqaJdU68l65FtPsG5oquDBgyeh/c+GHGu53pZ52D1QKaNGYWxCgtgFkuTWSTLNXxD1d9oBdpc5DguLJTNyZEPNVaenVTtC8rXosau48EnGT/S00fQipfbSmEd3/AfzGUWBKAfZk/C8CtEeABJuhqxMChPWCpj8E8Ch6mNHn7t/PHm8Nk1bfdjH5/nKwtIfTshmxl17EQcL0eKnopYDJ+lwny6aCjVm2gSSBLkYnmGe3W2yNOE9djhoowNh2/o8cdceSkGrzY+x+jpvf78="
    - apiuser=joerghall

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker run -v ${TRAVIS_BUILD_DIR}:/root/cbt-tool-ninja
  -e apipwd -e apiuser -e TRAVIS_BRANCH --rm -t jhhj/cbt-gcc-centos7:1 /bin/bash
  -c "mkdir /root/cbt-devtool-gcc/build && cd /root/cbt-tool-ninja/build && export PATH=/opt/rh/devtoolset-6/root/usr/bin:$PATH
  && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target publish_package"
  ; fi

